using UnityEngine;

public class Phase2_RoutingSetup : MonoBehaviour
{
    [ContextMenu("Execute Phase 2: Build Routing Tables")]
    public void BuildRoutingTables()
    {
        // 1. Grab everything generated by Phase 1
        IntersectionNode[] allNodes = FindObjectsByType<IntersectionNode>(FindObjectsInactive.Exclude, FindObjectsSortMode.None);
        TrafficEdge[] allEdges = FindObjectsByType<TrafficEdge>(FindObjectsInactive.Exclude, FindObjectsSortMode.None);

        if (allNodes.Length == 0 || allEdges.Length == 0)
        {
            Debug.LogError("No graph found! Please run Phase 1 first.");
            return;
        }

        // 2. Clear out any old routing data to ensure a fresh start
        foreach (IntersectionNode node in allNodes)
        {
            node.routingTable.Clear();
        }

        // 3. Loop through every Edge and wire up the neighbor nodes
        int connectionsMade = 0;

        foreach (TrafficEdge edge in allEdges)
        {
            if (edge.startNode == null || edge.endNode == null)
            {
                Debug.LogWarning($"[Graph Warning] Edge '{edge.edgeName}' is missing a start or end node. Skipping this edge.");
                continue;
            }

            IntersectionNode nodeA = edge.startNode;
            IntersectionNode nodeB = edge.endNode;

            // Wire Node A: "To get to B, take this edge"
            if (!HasRoute(nodeA, nodeB))
            {
                nodeA.routingTable.Add(new Route { destination = nodeB, edgeToTake = edge });
                connectionsMade++;
            }

            // Wire Node B -> "To get to A, take this edge."
            if (!HasRoute(nodeB, nodeA))
            {
                nodeB.routingTable.Add(new Route { destination = nodeA, edgeToTake = edge });
                connectionsMade++;
            }
        }

        Debug.Log($"Phase 2 Complete: Successfully wired {allEdges.Length} Edges across {allNodes.Length} Nodes.");
    }

    private bool HasRoute(IntersectionNode sourceNode, IntersectionNode targetNode)
    {
        foreach (Route route in sourceNode.routingTable)
        {
            if (route.destination == targetNode)
            {
                return true;
            }
        }
        return false;
    }
}