using UnityEngine;

public class Phase2_RoutingSetup : MonoBehaviour
{
    [ContextMenu("Execute Phase 2: Build Routing Tables")]
    public void BuildRoutingTables()
    {
        // 1. Grab everything generated by Phase 1
        IntersectionNode[] allNodes = FindObjectsByType<IntersectionNode>(FindObjectsInactive.Exclude, FindObjectsSortMode.None);
        TrafficEdge[] allEdges = FindObjectsByType<TrafficEdge>(FindObjectsInactive.Exclude, FindObjectsSortMode.None);

        if (allNodes.Length == 0 || allEdges.Length == 0)
        {
            Debug.LogError("No graph found! Please run Phase 1 first.");
            return;
        }

        // 2. Clear out any old routing data to ensure a fresh start
        foreach (IntersectionNode node in allNodes)
        {
            node.routingTable.Clear();
        }

        // 3. Loop through every Edge and wire up the neighbor nodes
        foreach (TrafficEdge edge in allEdges)
        {
            IntersectionNode nodeA = edge.startNode;
            IntersectionNode nodeB = edge.endNode;

            // Tell Node A: "If a car wants to go to Node B, it must take this Edge."
            if (!nodeA.routingTable.ContainsKey(nodeB))
            {
                edge.edgeName = $"Route_{nodeA.nodeID}_to_{nodeB.nodeID}";
                nodeA.routingTable.Add(nodeB, edge);
            }

            // Tell Node B: "If a car wants to go to Node A, it must take this Edge."
            if (!nodeB.routingTable.ContainsKey(nodeA))
            {
                edge.edgeName = $"Route_{nodeB.nodeID}_to_{nodeA.nodeID}";
                nodeB.routingTable.Add(nodeA, edge);
            }
        }

        Debug.Log($"Phase 2 Complete: Successfully wired {allEdges.Length} Edges across {allNodes.Length} Nodes.");
    }
}